import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// De sidebar wordt gegenereerd uit de mappenstructuur van website/docs/.
// Nieuwe documentatie toevoegen = een .md/.mdx-bestand in de juiste map zetten.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
